# Generated by Django 5.0.6 on 2025-03-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVUpload',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='impact',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='target_variable',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='weights',
            field=models.JSONField(default=dict),
        ),
    ]
